conf/urls.py
from django.contrib import admin
from django.urls import (
    path, include
)

from .views import HomeView

urlpatterns = [
    path('',
         HomeView.as_view(), name='home'),

    path('golf/',
         include('golf.urls', namespace='golf')),

    path('windmill/',
         include('windmill.urls', namespace='windmill')),

    path('accounts/',
         include('member.urls')),

    path('admin/',
         admin.site.urls),
]

golf/urls.py
from django.urls import path

from . import views

app_name = 'golf'

urlpatterns = [
    path('holiday-list/',
         views.HolidayListView.as_view(), name='holiday-list'),
]

member/urls.py
from importlib import import_module

from allauth.socialaccount import providers
from django.urls import (
    path, re_path
)

from . import views

# app_name = 'member'

urlpatterns = [
    # Account
    path('login/',
         views.MemberLoginView.as_view(), name="account_login"),
    path('logout/',
         views.MemberLogoutView.as_view(), name="account_logout"),

    # Social Providers
    path('social/login/cancelled/',
         views.MemberSocialLoginCancelledView.as_view(), name='socialaccount_login_cancelled'),
    path('social/login/error/',
         views.MemberSocialLoginErrorView.as_view(), name='socialaccount_login_error'),
    path('social/signup/',
         views.MemberSocialSignupView.as_view(), name='socialaccount_signup'),
    path('social/connections/',
         views.MemberSocialConnectionsView.as_view(), name='socialaccount_connections'),

    # Email Confirmation
    path('confirm-email/',
         views.MemberEmailVerificationSentView.as_view(), name="account_email_verification_sent"),
    re_path(r'^confirm-email/(?P<key>[-:\w]+)/$',
            views.MemberConfirmEmailView.as_view(), name="account_confirm_email"),
    path('email/',
         views.MemberEmailView.as_view(), name="account_email"),
]

# URL patterns for Line custom social providers
# Line provider requires PyJWT
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue

    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)

    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

windmill/urls.py
from django.urls import (
    path, re_path
)

from . import views

app_name = 'windmill'

urlpatterns = [
    path('tee-off-list/',
         views.TeeOffListView.as_view(), name='tee-off-list'),

    path('booking/add/',
         views.BookingCreateForm.as_view(), name='booking-create'),

    path('reports/',
         views.Report.as_view(), name='status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/$',
            views.YearlyStatusReport.as_view(), name='yearly-status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$',
            views.MonthlyStatusReport.as_view(), name='monthly-status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$',
            views.DailyStatusReport.as_view(), name='daily-status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/all/$',
            views.MonthlyDailyStatusReport.as_view(), name='monthly-daily-status-report'),
]

conf/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'conf/home.html'

conf/templates/conf/base.html
<!doctype html>
<html class="no-js" lang="ko">
{% load static %}
{% load i18n %}
<head>
    <meta charset="utf-8">
    <title>{% trans 'NA-ONE' %} : {% block title %}{% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="apple-touch-icon" href="icon.png">
    <!-- Place favicon.ico in the root directory -->

    {% block stylesheet %}
        <link rel="stylesheet"
              href="{% static "conf/css/webfonts/sarabun.css" %}">
        <link rel="stylesheet"
              href="{% static "conf/css/webfonts/nanum-gothic.css" %}">
        <link rel="stylesheet"
              href="{% static "conf/css/vendor/bootstrap.min.css" %}">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.css"
              integrity="sha256-46qynGAkLSFpVbEBog43gvNhfrOj+BmwXdxFgVK/Kvc=" crossorigin="anonymous"/>
        <link rel="stylesheet"
              href="{% static "conf/css/base.css" %}">
    {% endblock %}

    <meta name="theme-color" content="#78c2ad">
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">{% trans 'NA-ONE Communication' %}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">{% trans 'Home' %}</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% trans 'SWGC' %}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'windmill:booking-create' %}">{% trans 'Booking' %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'golf:holiday-list' %}">{% trans 'Thai Holidays' %}</a>
                    </div>
                </li>
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">{% trans 'Sign In' %}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">{% trans 'Profile' %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">{% trans 'Sign Out' %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<main>{% block content %}{% endblock %}</main>

<!-- Footer -->
<footer class="py-2 bg-info">
    <div class="container">
        <div class="row py-1">
            <div class="col-12 col-md-6 text-center text-md-right text-light">
                Copyright © 2017-{% now "Y" %} www.naonegolf.com
            </div>
            <div class="col-12 col-md-6 text-center text-md-left text-light">
                All Rights Reserved.
            </div>
        </div>
    </div>
    <!-- /.container -->
</footer>

{% if messages %}
    <div style="display:none">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
{% endif %}

{% block javascript %}
    <script type="text/javascript"
            src="{% static "conf/js/vendor/jquery-3.4.1.min.js" %}"></script>
    <script type="text/javascript"
            src="{% static "conf/js/vendor/bootstrap.bundle.min.js" %}"></script>
    <script type="text/javascript"
            src="{% static "conf/js/base.js" %}"></script>
    {{ form.media.js }}
{% endblock %}

</body>

</html>

conf/templates/conf/home.html
{% extends 'conf/base.html' %}

{% load static %}
{% load i18n %}

{% block title %}{% trans 'SWGC Booking' %}{% endblock %}

{% block content %}
    <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselIndicators" data-slide-to="1"></li>
            <li data-target="#carouselIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static "conf/images/windmill01.jpg" %}"
                     alt="Summit Windill Golf Club">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static "conf/images/windmill02.jpg" %}"
                     alt="Summit Windill Golf Club">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static "conf/images/windmill04.jpg" %}"
                     alt="Summit Windill Golf Club">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!-- Page Content -->
    <div class="container">
        <div class="card text-white bg-secondary my-4">
            <div class="card-body py-2">
                <p class="text-white m-0 no-break-word">
                    나원 커뮤니케이션은 태국 방콕 <strong>서밋 윈드밀 골프장 회원권</strong>을 소유 및 운영 관리하고
                    있습니다.
                </p>
                <p class="text-white mt-3 mb-0 no-break-word">
                    나원 커뮤니케이션은 고객 여러분과 신뢰를 위한 <strong>엄격한 시간 준수</strong>와
                    <strong>합리적인 가격 기준</strong>을 약속합니다.
                </p>
            </div>
        </div>

        <div class="row mb-4">
            <div class="col-12">
                <ul class="pl-4 no-break-word">
                    <li class="my-1">
                        나원 커뮤니케이션은 태국의 평일 기준 오전 8시 이후 티오프 3개, 9시 이후 티오프 3개, 10시 이후 티오프 1개를 확정하여 갖고 있습니다.
                    </li>
                    <li class="my-1">
                        나원 커뮤니케이션은 태국의 주말과 법정 공휴일 기준 오전 시간대 2개, 오후 12시 8분, 12시 16분, 12시 24분 3개 확정 티오프를 갖고 있습니다.
                    </li>
                    <li class="my-1">
                        평일 티오프는 30일 전부터 예약 확정이 가능하고 주말 또는 법정 공휴일의 티오프는 직전 월요일에 예약 확정이 가능합니다.
                    </li>
                </ul>
            </div>
        </div>
        <div class="row my-3">
        </div>
    </div>
    <!-- /.container -->
{% endblock %}

conf/templates/conf/snippets.html
{% extends 'conf/base.html' %}

{% load static %}

{% block title %}Relax and enjoy your life!{% endblock %}

{% block content %}
    <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselIndicators" data-slide-to="1"></li>
            <li data-target="#carouselIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="{% static "conf/images/windmill01.jpg" %}" alt="Summit Windill Golf Club">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static "conf/images/windmill02.jpg" %}" alt="Summit Windill Golf Club">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="{% static "conf/images/windmill04.jpg" %}" alt="Summit Windill Golf Club">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <!-- Page Content -->
    <div class="container">
        <div class="row my-4">
            <div class="col-12">
                <p class="lead">나원 커뮤니케이션은 태국 방콕 서밋 윈드밀 골프장의 무기명 회원권을 소유 및 관리하고 있습니다.</p>
                <ul class="no-break-word">
                    <li class="my-1">나원 커뮤니케이션은 태국의 평일 기준 오전 8시 이후 티오프 3개, 9시 이후 티오프 3개, 10시 이후 티오프 1개를 확정하여 갖고 있습니다.
                    </li>
                    <li class="my-1">나원 커뮤니케이션은 태국의 주말과 법정 공휴일 기준 오후 12시 8분, 12시 16분, 12시 24분 확정 티오프를 갖고 있습니다.</li>
                    <li class="my-1">평일 티오프는 30일 전부터 예약 확정이 가능하고 주말 또는 법정 공휴일의 티오프는 직전 월요일에 예약 확정이 가능합니다.</li>
                    <li class="my-1">นา-วัน คอมิวนิเคชั่น</li>
                </ul>
            </div>
        </div>

        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
            <h1 class="display-3">A Warm Welcome!</h1>
            <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt
                possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam
                repellat.</p>
            <a href="#" class="btn btn-primary btn-lg">Call to action!</a>
        </header>

        <!-- Page Features -->
        <div class="row text-center">

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Card title</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse
                            necessitatibus neque.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary">Find Out More!</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Card title</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni
                            sapiente, tempore debitis beatae culpa natus architecto.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary">Find Out More!</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Card title</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse
                            necessitatibus neque.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary">Find Out More!</a>
                    </div>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 mb-4">
                <div class="card h-100">
                    <img class="card-img-top" src="http://placehold.it/500x325" alt="">
                    <div class="card-body">
                        <h4 class="card-title">Card title</h4>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Explicabo magni
                            sapiente, tempore debitis beatae culpa natus architecto.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary">Find Out More!</a>
                    </div>
                </div>
            </div>

        </div>
        <!-- /.row -->


        <!-- Heading Row -->
        <div class="row align-items-center my-5">
            <div class="col-lg-7">
                <img class="img-fluid rounded mb-4 mb-lg-0" src="http://placehold.it/900x400" alt="">
            </div>
            <!-- /.col-lg-8 -->
            <div class="col-lg-5">
                <h1 class="font-weight-light">Business Name or Tagline</h1>
                <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it,
                    but it
                    makes a great use of the standard Bootstrap core components. Feel free to use this template for any
                    project you want!</p>
                <a class="btn btn-primary" href="#">Call to Action!</a>
            </div>
            <!-- /.col-md-4 -->
        </div>
        <!-- /.row -->

        <!-- Call to Action Well -->
        <div class="card text-white bg-secondary my-5 py-4 text-center">
            <div class="card-body">
                <p class="text-white m-0">This call to action card is a great place to showcase some important
                    information
                    or display a clever tagline!</p>
            </div>
        </div>

        <!-- Content Row -->
        <div class="row">
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Card One</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex
                            numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary btn-sm">More Info</a>
                    </div>
                </div>
            </div>
            <!-- /.col-md-4 -->
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Card Two</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quod tenetur ex
                            natus
                            at dolorem enim! Nesciunt pariatur voluptatem sunt quam eaque, vel, non in id dolore
                            voluptates
                            quos eligendi labore.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary btn-sm">More Info</a>
                    </div>
                </div>
            </div>
            <!-- /.col-md-4 -->
            <div class="col-md-4 mb-5">
                <div class="card h-100">
                    <div class="card-body">
                        <h2 class="card-title">Card Three</h2>
                        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem magni quas ex
                            numquam, maxime minus quam molestias corporis quod, ea minima accusamus.</p>
                    </div>
                    <div class="card-footer">
                        <a href="#" class="btn btn-primary btn-sm">More Info</a>
                    </div>
                </div>
            </div>
            <!-- /.col-md-4 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
{% endblock %}