conf/urls.py
from django.contrib import admin
from django.urls import (
    path, include
)

from .views import HomeView

urlpatterns = [
    path('',
         HomeView.as_view(), name='home'),

    path('golf/',
         include('golf.urls', namespace='golf')),

    path('windmill/',
         include('windmill.urls', namespace='windmill')),

    path('accounts/',
         include('member.urls')),

    path('admin/',
         admin.site.urls),
]

member/urls.py
from importlib import import_module

from allauth.socialaccount import providers
from django.urls import (
    path, re_path
)

from . import views

# app_name = 'member'

urlpatterns = [
    # Account
    path('login/',
         views.MemberLoginView.as_view(), name="account_login"),
    path('logout/',
         views.MemberLogoutView.as_view(), name="account_logout"),

    # Social Providers
    path('social/login/cancelled/',
         views.MemberSocialLoginCancelledView.as_view(), name='socialaccount_login_cancelled'),
    path('social/login/error/',
         views.MemberSocialLoginErrorView.as_view(), name='socialaccount_login_error'),
    path('social/signup/',
         views.MemberSocialSignupView.as_view(), name='socialaccount_signup'),
    path('social/connections/',
         views.MemberSocialConnectionsView.as_view(), name='socialaccount_connections'),

    # Email Confirmation
    path('confirm-email/',
         views.MemberEmailVerificationSentView.as_view(), name="account_email_verification_sent"),
    re_path(r'^confirm-email/(?P<key>[-:\w]+)/$',
            views.MemberConfirmEmailView.as_view(), name="account_confirm_email"),
    path('email/',
         views.MemberEmailView.as_view(), name="account_email"),
]

# URL patterns for Line custom social providers
# Line provider requires PyJWT
for provider in providers.registry.get_list():
    try:
        prov_mod = import_module(provider.get_package() + '.urls')
    except ImportError:
        continue

    prov_urlpatterns = getattr(prov_mod, 'urlpatterns', None)

    if prov_urlpatterns:
        urlpatterns += prov_urlpatterns

windmill/urls.py
from django.urls import (
    path, re_path
)

from . import views

app_name = 'windmill'

urlpatterns = [
    path('tee-off-list/',
         views.TeeOffListView.as_view(), name='tee-off-list'),

    path('booking/add/',
         views.BookingCreateForm.as_view(), name='booking-create'),

    path('reports/',
         views.Report.as_view(), name='status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/$',
            views.YearlyStatusReport.as_view(), name='yearly-status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/$',
            views.MonthlyStatusReport.as_view(), name='monthly-status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2})/$',
            views.DailyStatusReport.as_view(), name='daily-status-report'),

    re_path(r'^reports/(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/all/$',
            views.MonthlyDailyStatusReport.as_view(), name='monthly-daily-status-report'),
]

windmill/models.py
from decimal import Decimal

from django.core import validators
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import Choices
from model_utils import models as model_utils_models


class Agency(model_utils_models.TimeStampedModel):
    ENTITY_TYPE = Choices(
        (0, 'naone', _('NA-ONE')),
        (1, 'swgc', _('SWGC')),
        (2, 'member', _('SWGC Member')),
        (3, 'company', _('Company')),
    )

    TYPE_CHOICES = Choices(
        (0, 'normal', _('Normal')),
        (1, 'prepaid', _('Prepaid')),
    )

    entity = models.IntegerField(
        verbose_name=_('Agency entity type'),
        choices=ENTITY_TYPE,
        default=ENTITY_TYPE.company,
        db_index=True,
    )

    type = models.IntegerField(
        verbose_name=_('Pay type'),
        choices=TYPE_CHOICES,
        default=TYPE_CHOICES.normal,
        db_index=True,
    )

    name = models.CharField(
        verbose_name=_('Name'),
        max_length=255,
    )

    weekday_day = models.DecimalField(
        verbose_name=_('Weekday day'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    weekend_morning = models.DecimalField(
        verbose_name=_('Weekend morning'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    weekend_afternoon = models.DecimalField(
        verbose_name=_('Weekend afternoon'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    twilight = models.DecimalField(
        verbose_name=_('Twilight'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    night = models.DecimalField(
        verbose_name=_('Night'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    class Meta:
        verbose_name = _('Agency')
        verbose_name_plural = _('Agencies')

    def __str__(self):
        return '[{}/{}] {}'.format(self.get_entity_display(), self.get_type_display(), self.name)


class TeeOffTime(model_utils_models.TimeStampedModel):
    SEASON_CHOICES = Choices(
        (0, 'low', _('Low season')),
        (1, 'high', _('High season')),
    )

    DAY_CHOICES = Choices(
        (0, 'weekday', _('Weekday')),
        (1, 'weekend', _('Weekend')),
    )

    SLOT_CHOICES = Choices(
        (0, 'morning', _('Morning')),
        (1, 'daytime', _('Daytime')),
        (2, 'twilight', _('Twilight')),
        (3, 'night', _('Night')),
    )

    TYPE_CHOICES = Choices(
        (0, 'fixed', _('Fixed')),
        (1, 'stand_by', _('Stand-by'))
    )

    TEE_OFF_STATUS_CHOICES = Choices(
        (0, 'open', _('Open')),
        (1, 'held', _('Held')),
        (2, 'sold', _('Sold')),
        (3, 'revoked', _('Revoked')),
    )

    HOLE_CHOICES = Choices(
        (0, 'hole18', _('18 Holes')),
        (1, 'hole9', _('9 Holes')),
        (2, 'hole27', _('27 Holes')),
        (3, 'hole36', _('36 Holes')),
    )

    BOOKING_STATUS_CHOICES = Choices(
        (0, 'order_opened', _('order opened')),
        (1, 'order_pending', _('order pending')),
        (2, 'payment_pending', _('payment pending')),
        (3, 'completed', _('order complete')),
        (4, 'offered', _('order offered')),
        (5, 'voided', _('order voided')),
        (6, 'refund_requested', _('refund requested')),
        (7, 'refund_pending', _('refund pending')),
        (8, 'refunded1', _('order refunded(original)')),  # original order
        (9, 'refunded2', _('order refunded(reverse)')),  # refund order
    )

    agency = models.ForeignKey(
        'windmill.Agency',
        verbose_name=_('Agency'),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    customer_name = models.CharField(
        verbose_name=_('Customer name'),
        max_length=255,
    )

    pax = models.IntegerField(
        verbose_name=_('Pax'),
        default=4,
    )

    hole = models.IntegerField(
        verbose_name=_('No. of holes'),
        choices=HOLE_CHOICES,
        default=HOLE_CHOICES.hole18,
        db_index=True,
    )

    booking_status = models.IntegerField(
        verbose_name=_('Booking status'),
        choices=BOOKING_STATUS_CHOICES,
        default=BOOKING_STATUS_CHOICES.order_opened,
        db_index=True,
    )

    season = models.IntegerField(
        verbose_name=_('High/Low Season'),
        choices=SEASON_CHOICES,
        default=SEASON_CHOICES.high,
        db_index=True,
    )

    day_of_week = models.IntegerField(
        verbose_name=_('Day of week'),
        choices=DAY_CHOICES,
        default=DAY_CHOICES.weekday,
        db_index=True,
    )

    slot = models.IntegerField(
        verbose_name=_('Time slot'),
        choices=SLOT_CHOICES,
        default=SLOT_CHOICES.morning,
        db_index=True,
    )

    type = models.IntegerField(
        verbose_name=_('Tee off type'),
        choices=TYPE_CHOICES,
        default=TYPE_CHOICES.fixed,
        db_index=True,
    )

    tee_off_status = models.IntegerField(
        verbose_name=_('Tee off status'),
        choices=TEE_OFF_STATUS_CHOICES,
        default=TEE_OFF_STATUS_CHOICES.open,
        db_index=True,
    )

    day = models.DateField(
        verbose_name=_('Round day'),
        db_index=True,
    )

    time = models.TimeField(
        verbose_name=_('Tee-off time'),
    )

    phone = models.CharField(
        verbose_name=_('Telephone'),
        max_length=32,
        blank=True,
    )

    remarks = models.TextField(
        verbose_name=_('Remarks'),
        blank=True,
    )

    class Meta:
        verbose_name = _('Tee-off time')
        verbose_name_plural = _('Tee-off times')

    def __str__(self):
        return '{} {}'.format(self.day, self.time)

    @property
    def sales(self):
        total = 0

        for i in self.naoneassettransaction_set.all():
            if i.cash_flow == NaoneAssetTransaction.CASH_FLOW_CHOICES.cash_in:
                total += i.amount

        return f'{total:,}'

    sales.fget.short_description = _('Sales')

    @property
    def profit(self):
        total = 0

        for i in self.naoneassettransaction_set.all():
            if i.cash_flow == NaoneAssetTransaction.CASH_FLOW_CHOICES.cash_in:
                total += i.amount
            else:
                total -= i.amount

        return f'{total:,}'

    profit.fget.short_description = _('Profit')


class NaoneAsset(model_utils_models.TimeStampedModel):
    ASSET_TYPE_CHOICES = Choices(
        (0, 'petty_cash', _('Petty cash')),
        (1, 'prepaid', _('Prepaid')),
        (2, 'bank_account', _('Bank account')),
        (3, 'ecoupon', _('E-Coupon')),
    )

    asset_type = models.IntegerField(
        verbose_name=_('Asset type'),
        choices=ASSET_TYPE_CHOICES,
        default=ASSET_TYPE_CHOICES.petty_cash,
        db_index=True,
    )

    name = models.CharField(
        verbose_name=_('Asset name'),
        max_length=255,
    )

    balance = models.DecimalField(
        verbose_name=_('Asset balance'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    class Meta:
        verbose_name = _('NA-ONE Asset')
        verbose_name_plural = _('NA-ONE Assets')

    def __str__(self):
        return '{}'.format(self.name)


class NaoneAssetTransaction(model_utils_models.TimeStampedModel):
    FEE_CHOICES = Choices(
        (0, 'green_fee', _('Green fee')),
        (1, 'caddie_fee', _('Caddie fee')),
        (2, 'cart_fee', _('Cart fee')),
        (3, 'promotion', _('Promotion')),
    )

    CASH_FLOW_CHOICES = Choices(
        (0, 'cash_in', _('Cash-in')),
        (1, 'cash_out', _('Cash-out')),
    )

    INPUT_TYPE_CHOICES = Choices(
        (0, 'manual', _('Manual input')),
        (1, 'closing', _('Closing input')),
    )

    order = models.ForeignKey(
        'windmill.TeeOffTime',
        verbose_name=_('Tee-off'),
        db_index=True,
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )

    fee = models.IntegerField(
        verbose_name=_('Fee'),
        choices=FEE_CHOICES,
        default=FEE_CHOICES.green_fee,
        db_index=True,
    )

    cash_flow = models.IntegerField(
        verbose_name=_('Cash flow'),
        choices=CASH_FLOW_CHOICES,
        default=CASH_FLOW_CHOICES.cash_in,
        db_index=True,
    )

    input_type = models.IntegerField(
        verbose_name=_('Input type'),
        choices=INPUT_TYPE_CHOICES,
        default=INPUT_TYPE_CHOICES.manual,
        db_index=True,
    )

    asset = models.ForeignKey(
        'windmill.NaoneAsset',
        verbose_name=_('Asset'),
        db_index=True,
        on_delete=models.CASCADE,
    )

    unit_price = models.DecimalField(
        verbose_name=_('Unit price'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    amount = models.DecimalField(
        verbose_name=_('Amount'),
        max_digits=11,
        decimal_places=0,
        default=Decimal('0'),
        help_text=_('THB'),
    )

    transaction_date = models.DateTimeField(
        verbose_name=_('Transaction date'),
    )

    remarks = models.TextField(
        verbose_name=_('Remarks'),
        blank=True,
    )

    class Meta:
        verbose_name = _('Asset transaction')
        verbose_name_plural = _('Asset transactions')

    def __str__(self):
        return 'asset transaction - {} {}'.format(self.amount, self.transaction_date)


class NaoneManagingBook(model_utils_models.TimeStampedModel):
    ASSET_TYPE_CHOICES = Choices(
        (0, 'petty_cash', _('Petty cash')),
        (1, 'prepaid', _('Prepaid')),
        (2, 'ecoupon', _('E-Coupon')),
    )

    CASH_FLOW_CHOICES = Choices(
        (0, 'cash_in', _('Cash-in')),
        (1, 'cash_out', _('Cash-out')),

windmill/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from . import models


class TeeOffTimeAdminForm(forms.ModelForm):
    sales = forms.FloatField(
        label=_('Sales'),
        required=False,
    )

    profit = forms.FloatField(
        label=_('Profit'),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super(TeeOffTimeAdminForm, self).__init__(*args, **kwargs)

    class Meta:
        model = models.TeeOffTime
        fields = '__all__'

windmill/templates/windmill/daily_status_report.html
{% extends 'conf/base.html' %}

{% load static i18n humanize %}
{% load windmill_filters %}

{% block title %}{% trans 'Daily Status Report' %}{% endblock %}

{% block content %}
<div class="container">
    {% for item in tee_off_times %}
    <div class="row border-bottom mt-5 booking-heading">
        <div class="col-md-4 col-12">
            {% if user.is_superuser %}
            <a href="{% url 'admin:windmill_teeofftime_change' item.id %}" class="text-dark">
                {{ forloop.counter }} {{ item.agency }} / {{ item.customer_name }}
            </a>
            {% else %}
            {{ forloop.counter }} {{ item.agency }} / {{ item.customer_name }}
            {% endif %}
        </div>
        <div class="col-md-2 col-6">
            {{ item.day|date:'Y-m-d' }}
            {{ item.time|time:'H:i' }}
        </div>
        <div class="col-md-1 col-3">
            {{ item.get_hole_display }}
        </div>
        <div class="col-md-1 col-3">
            {{ item.pax }} PAX
        </div>
        <div class="col-md-2 col-8">
            <span class="badge badge-primary">{{ item.get_booking_status_display }}</span>
        </div>
        <div class="col-md-2 col-4 text-right">
            {{ item.sales }} {% trans 'THB' %}
        </div>
    </div>
    {% for transaction in item.naoneassettransaction_set.all %}
    {% if transaction.cash_flow == transaction.CASH_FLOW_CHOICES.cash_in %}
    <div class="row border-bottom blue-text">
        {% else %}
        <div class="row border-bottom red-text">
            {% endif %}
            <div class="col-md-3 col-4">
                {{ transaction.get_fee_display }}
            </div>
            <div class="col-md-2 col-4">
                {{ transaction.get_cash_flow_display }}
            </div>
            <div class="col-md-3 col-4">
                {{ transaction.asset }}
            </div>
            <div class="col-md-4 col-12 text-right">
                {{ transaction.unit_price|floatformat:0|intcomma }} {% trans 'THB' %}
                x {{ item.pax }}
                = {{ transaction.amount|floatformat:0|intcomma }} {% trans 'THB' %}
            </div>
        </div>
        {% endfor %}
        <div class="row pettycash-text">
            <div class="col-md-8 col-4">
                {% trans 'Petty cash' %}
            </div>
            <div class="col-md-2 col-4">
                {% if item.total_petty_cash_in %}
                +{{ item.total_petty_cash_in|floatformat:0|intcomma }}
                {% else %}
                0
                {% endif %}
                {% trans 'THB' %}
            </div>
            <div class="col-md-2 col-4 text-right">
                {% if item.total_petty_cash_out %}
                -{{ item.total_petty_cash_out|floatformat:0|intcomma }}
                {% else %}
                0
                {% endif %}
                {% trans 'THB' %}
            </div>
        </div>
        {% endfor %}
        <div class="row my-5 font-weight-bold">
            <div class="col-md-2 col-6">
                {% trans 'Daily sales' %}
            </div>
            <div class="col-md-2 col-6 text-right">
                {{ total_sales|floatformat:0|intcomma }} {% trans 'THB' %}
            </div>
            <div class="col-md-2 col-6">
                {% trans 'Daily cost' %}
            </div>
            <div class="col-md-2 col-6 text-right">
                {{ total_cost|floatformat:0|intcomma }} {% trans 'THB' %}
            </div>
            <div class="col-md-2 col-6">
                {% trans 'Daily profit' %}
            </div>
            <div class="col-md-2 col-6 text-right">
                {{ total_profit|floatformat:0|intcomma }} {% trans 'THB' %}
            </div>
        </div>
        <div class="row">
            <div class="col">
                <a class="btn btn-block btn-primary"
                   href="{% url 'windmill:monthly-status-report' year month %}">{{ year }} - {{ month|month_name }}</a>
            </div>
        </div>
        <div class="row my-5">
            <div class="col">
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block stylesheet %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'windmill/css/windmill.css' %}">
{% endblock %}

windmill/templates/windmill/monthly_daily_status_report.html
{% extends 'conf/base.html' %}

{% load static i18n humanize %}
{% load windmill_filters %}

{% block title %}{% trans 'Daily Status Report' %}{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="row border-bottom mt-5 booking-heading">
        <div class="col">
            <table class="table table-responsive monthly-daily-status-report-table">
                <thead>
                <tr>
                    <th>라운드일</th>
                    <th>요일</th>
                    <th>상태</th>
                    <th>분류</th>
                    <th>예약자명</th>
                    <th>인원</th>
                    <th>티오프</th>
                    <th>ST</th>
                    <th>그린피</th>
                    <th>그.총액</th>
                    <th>그.자산</th>
                    <th>그.비용</th>
                    <th>그.총비용</th>
                    <th>캐디피</th>
                    <th>캐.총액</th>
                    <th>캐.자산</th>
                    <th>캐.비용</th>
                    <th>캐.총비용</th>
                    <th>카트피</th>
                    <th>카.총액</th>
                    <th>카.자산</th>
                    <th>카.비용</th>
                    <th>카.총비용</th>
                    <th>카.차감</th>
                    <th>카.자산</th>
                    <th>매출</th>
                    <th>수익</th>
                    <th>현장수금액 시재증액</th>
                    <th>현장수금액 시재차감</th>
                    <th>일시재증감</th>
                    <th>선납액증감</th>
                    <th>통장잔고증감</th>
                </tr>
                </thead>
                <tbody>
                {% for t in tee_off_times %}
                <tr>
                    <td>
                        {% if user.is_superuser %}
                        <a href="{% url 'admin:windmill_teeofftime_change' t.id %}" class="text-dark">
                            {{ t.day|date:'Ymd' }}
                        </a>
                        {%else %}
                        {{ t.day|date:'Ymd' }}
                        {%endif %}
                    </td>
                    <td>{{ t.day|date:'D' }}</td>
                    <td>{{ t.get_booking_status_display }}</td>
                    <td>{{ t.agency.name }}</td>
                    <td>{{ t.customer_name }}</td>
                    <td>{{ t.pax }}</td>
                    <td>{{ t.time|date:'H:i' }}</td>
                    <td>{{ t.get_type_display }}</td>
                    <td>{{ t.green_fee_price|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.green_fee_subtotal|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.green_fee_asset|asset_name }}</td>
                    <td>{{ t.green_fee_cost|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.green_fee_cost_subtotal|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.caddie_fee_price|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.caddie_fee_subtotal|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.caddie_fee_asset|asset_name }}</td>
                    <td>{{ t.caddie_fee_cost|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.caddie_fee_cost_subtotal|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.cart_fee_price|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.cart_fee_subtotal|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.cart_fee_asset|default:'-'|asset_name }}</td>
                    <td>{{ t.cart_fee_cost|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.cart_fee_cost_subtotal|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.ecard }}</td>
                    <td>{{ t.cart_fee_cost_asset|default:'-'|asset_name }}</td>
                    <td>{{ t.sales }}</td>
                    <td>{{ t.profit }}</td>
                    <td>{{ t.total_petty_cash_in|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.total_petty_cash_out|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.total_petty_cash_balance|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.total_prepaid_balance|default_if_none:'0'|intcomma }}</td>
                    <td>{{ t.total_bank_balance|default_if_none:'0'|intcomma }}</td>
                </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td>누계</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>{{ total_pax|default_if_none:'0'|intcomma }}</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>{{ total_ecard|default_if_none:'0'|intcomma }}</td>
                    <td>&nbsp;</td>
                    <td>{{ total_sales|default_if_none:'0'|intcomma }}</td>
                    <td>{{ total_profit|default_if_none:'0'|intcomma }}</td>
                    <td>{{ total_petty_cash_in|default_if_none:'0'|intcomma }}</td>
                    <td>{{ total_petty_cash_out|default_if_none:'0'|intcomma }}</td>
                    <td>{{ total_petty_cash_balance|default_if_none:'0'|intcomma }}</td>
                    <td>{{ total_prepaid_balance|default_if_none:'0'|intcomma }}</td>
                    <td>{{ total_bank_balance|default_if_none:'0'|intcomma }}</td>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <a class="btn btn-block btn-primary"
               href="{% url 'windmill:monthly-status-report' year month %}">{{ year }} - {{ month|month_name }}</a>
        </div>
    </div>
    <div class="row my-5">
        <div class="col">
        </div>
    </div>
</div>
{% endblock %}

{% block stylesheet %}
{{ block.super }}
<link href="{% static 'windmill/css/windmill.css' %}" rel="stylesheet">
{% endblock %}

windmill/templates/windmill/monthly_status_report.html
{% extends 'conf/base.html' %}

{% load static i18n humanize %}
{% load windmill_filters %}
{% load windmill_tags %}

{% block title %}{% trans 'Monthly Status Report' %}{% endblock %}

{% block content %}
    <div class="container">
        <h5 class="my-2">{% trans 'Monthly Status Report' %} - {{ year }} - {{ month|month_name }}</h5>
        <div class="row border-bottom my-1">
            {% for day in days %}
                <div class="col-md-12 col-12 my-1">
                    <a href="{% url 'windmill:daily-status-report' year month day.day|stringformat:"02d" %}"
                       class="{% if this_year and this_month == month %}font-weight-bold text-danger{% endif %}">
                        {% get_date year month day.day %}
                        {% if day.count > 0 %}<span class="badge badge-danger">{{ day.count }}</span>{% endif %}
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col">
                <a class="btn btn-block btn-primary"
                   href="{% url 'windmill:yearly-status-report' year %}">{{ year }}</a>
            </div>
        </div>
        <div class="row my-5">
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}

windmill/templates/windmill/report.html
{% extends 'conf/base.html' %}

{% load static i18n humanize %}

{% block title %}{% trans 'Status Report' %}{% endblock %}

{% block content %}
    <div class="container">
        <h5 class="my-2">{% trans 'Status Report' %}</h5>
        {% for year in years %}
            <div class="row border-bottom my-2">
                <div class="col-md-1 col-4">
                    <a href="{% url 'windmill:yearly-status-report' year %}">{{ year }}</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

windmill/templates/windmill/yearly_status_report.html
{% extends 'conf/base.html' %}

{% load static i18n humanize %}
{% load windmill_filters %}

{% block title %}{% trans 'Yearly Status Report' %}{% endblock %}

{% block content %}
    <div class="container">
        <h5 class="my-2">{% trans 'Yearly Status Report' %} - {{ year }}</h5>
        <div class="row border-bottom my-3">
            {% for month in months %}
                <div class="col-md-2 col-12">
                    <a href="{% url 'windmill:monthly-status-report' year month|stringformat:"02d" %}"
                       class="{% if this_year and this_month == month %}font-weight-bold text-danger{% endif %}">
                        {{ year }} - {{ month|month_name }}
                    </a>
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <div class="col">
                <a class="btn btn-block btn-primary"
                   href="{% url 'windmill:status-report' %}">{% trans 'All years' %}</a>
            </div>
        </div>
        <div class="row my-5">
            <div class="col">
            </div>
        </div>
    </div>
{% endblock %}